[toolchain]

[features]
resolution = true
skip-lint = false

[programs.localnet]
escrow = "8FaoxeYRcZZwtKnLdDrVnHW3dkNkDJSVECUk7jy4d1WL"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "/Users/pow/Documents/solana-developers-program/mysolanaRepo/C2_Comets_Andrei_A/Lab9-10/escrow/keypair.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/escrow.ts"
